# Generated by Django 3.0.7 on 2022-11-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contact_us_tbl',
        ),
    ]
